### ISSUE TITLE
Domain list is out of date when compared to the source.

### ISSUE THREAD

**Issue by craigcarlyle** [ihmpavel/free-email-domains-list#265]
Hi @ihmpavel, first of all, thanks for the library!

Secondly, there have been some additional domains added to [the source list](https://gist.github.com/okutbay/5b4974b70673dfdcc21c517632c1f984) since the last release. Is it possible to create a new release with the latest version of the list, please? 🙂 🙏

**Comment by ihmpavel** [comment]
Hi @craigcarlyle,

I have released new version [1.0.13](https://github.com/ihmpavel/free-email-domains-list/releases/tag/v1.0.13) with updated list.
